use PizzaOnline

--INSERT PRODUCT
insert [dbo].tProduct ([Product_ID], [Name], [Description], [Image], [Deleted], [Last_Modified_date], [Last_Modified_by], [Created_date], [Created_by], [Category_ID]) values 
(301, N'Bánh Mì Bơ Tỏi', N'Bánh mì nướng giòn cùng bơ tỏi', 'banh_mi_bo_toi.jpg', 0, null, null, null, null, 2),
(302, N'Nachos', N'Bánh Nachos giòn rụm kiểu Mexico chấm xốt phô mai thơm béo hoặc xốt cà chua đặc biệt', 'nachos.jpg', 0, null, null, null, null, 2),
(303, N'Xúp Kem Nấm Thịt Gà', N'Xúp kem với thịt gà, nấm và ngò tây', 'sup_kem_nam_thit_ga.jpg', 0, null, null, null, null, 2),
(304, N'Khoai Tây Chiên', N'Khoai tây chiên giòn', 'khoai_tay_chien.jpg', 0, null, null, null, null, 2),
(305, N'Xúp Hải Sản', N'Xúp hải sản', 'xup_hai_san.jpg', 0, null, null, null, null, 2),
(306, N'Bánh Cuộn Phô Mai', N'Bánh cuộn phô mai', 'banh_cuon_pho_mai.jpg', 0, null, null, null, null, 2),
(307, N'Bắp Nướng Phô Mai Thịt Xông Khói', N'Bắp ngọt phủ phô mai đút lò với thịt xông khói', 'bap_nuong_pho_mai_thit_xong_khoi.jpg', 0, null, null, null, null, 2),
(308, N'Cơm Chiên Tôm Vị Cay', N'Cơm chiên tỏi với tôm, đậu bi, cà rốt và bắp ngọt', 'com_chien_tom_vi_cay.jpg', 0, null, null, null, null, 2),
(309, N'Khoai Tây Chiên Đút Lò', N'Khoai tây chiên đút lò với phô mai, thịt xông khói và xốt mù tạt mật ong.', 'khoai_tay_chien_dut_lo.jpg', 0, null, null, null, null, 2),
(310, N'Phô Mai Chiên Giòn', N'Phô mai chiên giòn', 'pho_mai_chien_gion.jpg', 0, null, null, null, null, 2),
(311, N'Xà Lách Trộn Cá Ngừ Và Thịt Xông Khói', N'Xà lách trộn cá ngừ, thịt xông khói, đậu Pháp, cà chua bi, bắp với xốt dầu dấm và mayonaise', 'xa_lach_tron_ca_ngu_va_thit_xong_khoi.jpg', 0, null, null, null, null, 2),
(312, N'Xà Lách Gà Pesto', N'Xà lách, cà chua bi, rau mầm với thịt gà nướng và xốt pesto kiểu Ý, phủ phô mai parmesan', 'xa_lach_ga_pesto.jpg', 0, null, null, null, null, 2),
(313, N'Xà Lách Da Cá Hồi', N'Xà lách, cà chua bi, ớt chuông nướng, da cá hồi với xốt mè rang đặc biệt', 'xa_lach_da_ca_hoi.jpg', 0, null, null, null, null, 2),
(314, N'Mỳ Ý Thịt Xông Khói Xốt Kem', N'Mì Ý xốt kem với thịt heo xông khói, cà chua bi, hành tây và ngò tây', 'mi_y_thit_xong_khoi_xot_kem.jpg', 0, null, null, null, null, 2),
(315, N'Cơm Chiên Hải Sản', N'Cơm chiên tỏi với tôm, mực, nấm, cà rốt và đậu', 'com_chien_hai_san.jpg', 0, null, null, null, null, 2),
(316, N'Cơm Xúc Xích Nướng Phô Mai', N'Cơm đút lò với phô mai, xúc xích, thịt bò, dùng kèm cà rốt, đậu, hành tây, bắp với lớp phủ mè rang hấp dẫn', 'com_xuc_xich_nuong_pho_mai.jpg', 0, null, null, null, null, 2),
(317, N'Xúc Xích Ý Nướng', N'Xúc xích Ý nướng', 'xuc_xich_y_nuong.jpg', 0, null, null, null, null, 2),
(318, N'Mực Chiên Giòn', N'Mực khoanh tẩm bột chiên giòn', 'muc_chien_gion.jpg', 0, null, null, null, null, 2),
(319, N'Cơm Hải Sản Đút Lò', N'Baked pesto rice with cheese, shrimps, squids and carrots, beans, onions, corns, finished with sesames', 'com_hai_san_dut_lo.jpg', 0, null, null, null, null, 2),
(320, N'Xà Lách Tôm Nướng Đào', N'Xà lách, đào, ớt chuông, oliu với tôm nướng bơ tỏi dùng kèm bánh mì giòn', 'xa_lach_tom_nuong_dao.jpg', 0, null, null, null, null, 2),
(321, N'Cơm Cánh Gà BBQ', N'Cơm Chiên Tỏi Với Cánh Gà BBQ Nóng Hổi Thơm Nồng', 'com_canh_ga_bbq.jpg', 0, null, null, null, null, 2),
(322, N'Mì Ý Bò Bằm Xốt Cà Chua', N'Mì Ý bò bằm xốt cà chua', 'mi_y_bo_bam_xot_ca_chua.jpg', 0, null, null, null, null, 2),
(323, N'Mỳ Ý Tôm Và Xúc Xích', N'Mì Ý xốt kem với tôm, xúc xích và cà rốt.', 'my_y_tom_va_xuc_xich.jpg', 0, null, null, null, null, 2),
(324, N'Mì Ý Hải Sản Xốt Cà Chua', N'Mì Ý xốt cà chua với tôm, mực, hành tây và ớt chuông', 'mi_y_hai_san_xot_ca_chua.jpg', 0, null, null, null, null, 2),
(325, N'Mì Ý Hải Sản Xốt Tiêu Đen', N'Mì Ý với tôm, thanh cua, mực, nấm, ớt chuông, đậu và xốt tiêu đen', 'my_y_hai_san_xot_tieu_den.jpg', 0, null, null, null, null, 2)

--INSERT PRODUCTDETAIL
insert [dbo].tProductDetail([ProductDetail_ID], [Number], [Price], [Created_by], [Created_date], [Last_Modified_by], [Last_Modified_date], [Deleted], [Product_ID], [Size_ID], [Crust_ID]) values
(301, 10, 29000, null, null, null, null, 0, 301, 2, 2),
(302, 10, 29000, null, null, null, null, 0, 302, 2, 2),
(303, 10, 49000, null, null, null, null, 0, 303, 2, 2),
(304, 10, 59000, null, null, null, null, 0, 304, 2, 2),
(305, 10, 69000, null, null, null, null, 0, 305, 2, 2),
(306, 12, 69000, null, null, null, null, 0, 306, 2, 2),
(307, 12, 79000, null, null, null, null, 0, 307, 2, 2),
(308, 12, 79000, null, null, null, null, 0, 308, 2, 2),
(309, 12, 79000, null, null, null, null, 0, 309, 2, 2),
(310, 12, 79000, null, null, null, null, 0, 310, 2, 2),
(311, 13, 79000, null, null, null, null, 0, 311, 2, 2),
(312, 13, 79000, null, null, null, null, 0, 312, 2, 2),
(313, 13, 89000, null, null, null, null, 0, 313, 2, 2),
(314, 13, 90000, null, null, null, null, 0, 314, 2, 2),
(315, 13, 99000, null, null, null, null, 0, 315, 2, 2),
(316, 14, 99000, null, null, null, null, 0, 316, 2, 2),
(317, 14, 99000, null, null, null, null, 0, 317, 2, 2),
(318, 14, 99000, null, null, null, null, 0, 318, 2, 2),
(319, 14, 99000, null, null, null, null, 0, 319, 2, 2),
(320, 14, 99000, null, null, null, null, 0, 320, 2, 2),
(321, 15, 129000, null, null, null, null, 0, 321, 2, 2),
(322, 15, 120000, null, null, null, null, 0, 322, 2, 2),
(323, 15, 120000, null, null, null, null, 0, 323, 2, 2),
(324, 15, 130000, null, null, null, null, 0, 324, 2, 2),
(325, 15, 130000, null, null, null, null, 0, 325, 2, 2)